openapi: 3.1.0
info:
  title: Portfolio Retrieval API
  summary: REST APIs for managing user portfolios
  version: '1.0'
servers:
  - url: "http://localhost:9000"
    description: Local development environment
paths:
  /portfolio:
    post:
      operationId: create-portfolio
      description: Create a new portfolio for the authenticated user.
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Portfolio"
      responses:
        201:
          description: Portfolio successfully created.
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Portfolio"
        400:
          description: Invalid request data.
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: Authentication error.
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Error"
    get:
      operationId: get-portfolio
      description: Retrieve the portfolio of the authenticated user.
      responses:
        200:
          description: Successfully retrieved the portfolio.
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Portfolio"
        401:
          description: Authentication error.
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Portfolio not found.
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Internal server error.
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Portfolio:
      type: object
      properties:
        portfolioID:
          type: string
          description: Unique identifier for the portfolio.
        totalValue:
          type: number
          description: The total value of the portfolio.
        assets:
          type: array
          description: A list of assets in the portfolio.
          items:
            $ref: "#/components/schemas/Asset"
    Asset:
      type: object
      properties:
        asset_id:
          type: string
          description: Unique identifier for the cryptocurrency
        asset_name:
          type: string
          description: Name of the cryptocurrency
        symbol:
          type: string
          description: Symbol of the cryptocurrency
        quantity:
          type: number
          description: Quantity of the asset owned
        price:
          type: number
          format: double
          description: Current market price of the asset
        total_value:
          type: number
          format: double
          description: Current total value of the asset (quantity * current price)

    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code.
        message:
          type: string
          description: Error message.
