openapi: 3.1.0
info:
  title: User Management API for CryptoVault
  version: 1.0.0
  summary: "User Authentication"
  description: "API for user login and authentication."

paths:
  /api/users/login:
    post:
      summary: "Authenticate a user"
      description: "Authenticates a user using the provided userID or email and password."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userID:
                  type: string
                  description: "The userID or email of the user"
                password:
                  type: string
                  description: "The user's password"
              required:
                - userID
                - password
      responses:
        '200':
          description: "User authenticated successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: "JWT or another type of authentication token"
        '401':
          description: "Unauthorized"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "Authentication failed message"
              examples:
                invalid_credentials:
                  summary: "Invalid credentials"
                  value:
                    error: "Invalid userID or password."
        '500':
          description: "Internal server error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "Description of the server error"
              example:
                error: "An unexpected error occurred on the server."
